### ISSUE TITLE
Confusing logs: Within a STARTTLS session: "Server does not support STARTTLS"

### ISSUE THREAD

**Issue by tempuser5432** [corecode/dma#103]
After starting a STARTTLS session, an additional EHLO command is sent by DMA. Its response is parsed and certain information is printed to the logs.

There are servers that do not advertise STARTTLS within an already active STARTTLS session. Example: smtp.office365.com (one may use openssl s_client to check this).

For these kind of servers, the logs are something like the following:
* "Server supports STARTTLS"
* "SSL initialization successful"
* "Server does not support STARTTLS"

which may be considered confusing.

Please let me know if there is a misunderstanding on my side about this issue being _only_  relevant for the logs.

**Comment by corecode** [comment]
these are DEBUG log messages and can be ignored.
