### ISSUE TITLE
MASQUERADE newhost does not override -f user@host

### ISSUE THREAD

**Issue by ian-abbott** [corecode/dma#114]
Some `mail` programs (such as the one from GNU mailutils) run sendmail with the `-f username@host` option. If `MASQUERADE` is set to just a hostname (so that `config.masquerade_user` is null and `config.masquerade_host` is non-null), the host from the `-f` option is used as-is and does not get replaced with the masqueraded host name when constructing the envelope 'from' address.

**Comment by emaste** [comment]
For reference, from dma.8:
```
           If ‘MASQUERADE’ does not contain a @ sign, the string is
           interpreted as a host name.  For example, setting ‘MASQUERADE’ to
           ‘john@’ on host ‘hamlet’ will send all mails as ‘john@hamlet’;
           setting it to ‘percolator’ will send all mails as
           ‘username@percolator’.
```

I'll try to take a look at the patch soon, if @corecode doesn't manage to do it first.
