### ISSUE TITLE
aliases / MASQUERADE problem

### ISSUE THREAD

**Issue by victorclaessen** [corecode/dma#119]
### problem

I am trying to forward all mail on a host to one external email address (so that mail from cronjobs etc. will be delivered to my external mailbox). This is not working because the messages are not accepted for delivery by the smarthost because the recipient is not known. It looks like dma is not parsing the aliases file correctly? Or what am I doing wrong? It seems like victor@backup (the computer I am trying this on is called _backup_) is not being translated to victor@myhost.nl.  I am not sure if this is related to #117, but while trying to compile the latest version also I also ran in to problems (#118).

I send a test mail like this:
```
victor@backup:~# date | mail -s "Test Subject" victor
```

And then I get this **bounce message** in my spam folder on my external email address.
```
The original message was received at Wed, 11 Jan 2023 11:36:58 +0100
from [smtp.myhost.nl](http://smtp.myhost.nl/) [131.xxx.yyy.zzz]

   ----- The following addresses had permanent fatal errors -----
<victor@backup>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <victor@backup>... Host unknown (Name server: backup: host not found)

---------- Forwarded message ----------
From: <[victor@smtp.myhost.nl](mailto:victor@myhost.nl)>
To: <victor@backup>
Cc: 
Bcc: 
Date: Wed, 11 Jan 2023 11:36:58 +0100
Subject: Test Subject
Wed 11 Jan 2023 11:36:58 AM CET
```

### configuration
On Debian v11.6, I installed the most recently packed version (package 0.13-1). (```apt install dma```) 

**/etc/dma/dma.conf**
```
SMARTHOST my.smtp.server
PORT 587
AUTHPATH /etc/dma/auth.conf
SECURETRANSFER
STARTTLS
MAILNAME /etc/mailname
MASQUERADE victor@myhost.nl
```

**/etc/dma/auth.conf**
```
victor@smtp.myhost.nl|smtp.myhost.nl:mypassword
```

**/etc/aliases**
```
*: victor@myhost.nl
```

**Comment by corecode** [comment]
This looks like your smartserver is checking whether the origin host (EHLO hostname) has a name server address.  Either you need to disable this check for authenticated connections, or maybe dma doesn't use authentication (should be able to check syslog).

**Comment by corecode** [comment]
Looks like the server accepts the mail.  I would say this is a configuration issue on the smarthost side.

**Comment by corecode** [comment]
it says `envelope_from=<victor@myhost.nl>`, that means it did the masquerade.

Do you use the smarthost in any other form, e.g. from a mail client like Thunderbird?  Do you maybe have to use the `submission` port instead of straight `smtp`?

**Comment by victorclaessen** [comment]
Ah you are totally right, I should have said I'm not sure that the aliasing is being done right, since it's the receiver's address that is not being changed (in the log it says the mail is for victor@backup, and not for victor@myhost.nl).

I am now wondering if my `/etc/aliases` is correct?

The 587 port I am using is the submission port.

**Comment by victorclaessen** [comment]
I explicitly added victor@backup to `/etc/aliases` now, and that still gives the same result.
```
# /etc/aliases
*: victor@myhost.nl
victor@backup: victor@myhost.nl
```

**Comment by victorclaessen** [comment]
Ah, got it; using **strace -f** I found out what happens (although I must admit I do not understand the logic behind it).

When I send a mail, it calls **dma** which forks to **sendmail**, which tries to deliver the email.

**sendmail** is the one checking `/etc/aliases`, but first it reads `/etc/mailhost`, and appends the contents of that file to the local user for alias checking. In `/etc/mailhost` it said **myhost.nl**, so **sendmail** ends up checking `/etc/aliases` for **victor@myhost.nl** (instead of **victor@backup**), which was not there, so no alias is applied. It then proceeds to send the mail to **victor@backup** (instead of **victor@myhost.nl**) anyway. That's the part I don't understand.
But when I changed `/etc/mailhost` to contain **backup**, the aliasing came into effect and mail to **victor** was successfully delivered to **victor@myhost.nl**.

Thanks for your help.

**Comment by corecode** [comment]
That means you have configured dma to use `MAILNAME /etc/mailhost`.

Because you have configured a smarthost, all mail will go to the smarthost, even if it is addressed to `victor@backup`, the role of the smarthost is to figure out what to do with that.

**Comment by victorclaessen** [comment]
Ah, indeed if I remove `MAILNAME` from the config, then the value of /etc/mailhost is not relevant anymore!
