### ISSUE TITLE
Greeting message check for STARTTLS/AUTH availability

### ISSUE THREAD

**Issue by tuxillo** [corecode/dma#15]
dma does not read the server greeting to determine whether 
STARTTLS or AUTH are available (minor problem as this probably is 
just a configuration problem because only one "smarthost" is 
contacted).

Spotted in : http://bugs.dragonflybsd.org/issues/953

**Comment by mtremer** [comment]
I worked on a patch to implement this. Are you interested in merging this upstream?

http://git.ipfire.org/?p=people/ms/dma.git;a=commitdiff;h=54af6a9684f21d799de17d49f8b985d95f121080

**Comment by corecode** [comment]
Thanks for the patch.  Could you please submit a pull request - I have some comments I'd like to share with you.

**Comment by mtremer** [comment]
Thank you. Please see #34.

**Comment by jjakob** [comment]
Debian Buster still has version 0.11 which does not include the patch from #34. I was able to download the 0.13-1 deb package from https://packages.debian.org/sid/dma and install it with dpkg, luckily all the dependencies were the same. This fixed the error messages and I'm not getting banned by fail2ban on the mail server any more after it sees the failed login attempts.

**Comment by corecode** [comment]
Thanks for confirming!
