### ISSUE TITLE
Error "dma: could not open flush file": flush file got perms 440

### ISSUE THREAD

**Issue by blueyed** [corecode/dma#23]
I've installed dma locally (and dkpg-diverted the `/usr/sbin/dma` binary).

While `dma` kept working in general (e.g. with `mail ...`), the following errors appeared regularly in `mail.log`, probably from the munin process:

> dma: could not open flush file: Permission denied

I've tried `sudo -u munin mail ...`, but this worked.

The flush file looks like this:

    -r--r----- 1 mail mail 0 Sep 22 17:20 /var/spool/dma/flush

After removing it, it got recreated and the errors went away:

    -rw-r----- 1 mail mail 0 Sep 22 18:05 /var/spool/dma/flush

It seems that somehow the `flush` file has been created with wrong permisisons.

**Comment by zpin** [comment]
It looks like v0.9 shipped with Debian creates the file with 440. A compile of the current master creates it with 640 after just replacing the binary on a Debian installation of the package.

**Comment by blueyed** [comment]
@zpin 
Thanks for this information.

Is it a problem with 0.9 in general or with the Debian package then?
I've searched the Debian patches for `chmod|440`, but found nothing.

**Comment by zpin** [comment]
It looks like it's an issue with dma 0.9, when I put the 0.9 binary back in place, remove the file and run dma -q it creates the file with 440 again:
https://github.com/corecode/dma/blob/v0.9/spool.c#L432

**Comment by blueyed** [comment]
It was apparently fixed in 3f9fdc0f6.

**Comment by blueyed** [comment]
That was commit on 25 Jul 2013 already.
Time for a new release maybe then? :)

**Comment by corecode** [comment]
released v0.10
