### ISSUE TITLE
Simple local DoS with dma

### ISSUE THREAD

**Issue by feld** [corecode/dma#29]
Hello,

I was browsing my twitter feed when OpenSMTPD was requesting people spam their test box with emails.

    $ jot 10000 | while read line; do echo eat duck | mail -s 'duck you' discard@test.opensmtpd.org; done

I ran this on a few of my spare boxes, a few of which were using dma. On one particular box with lower resources my SSH connection disconnected. Strange! After logging back in and getting a few alerts from my monitoring I realized some daemons were no longer running. Turns out, you can trick dma into running send-mail processes until the system runs out of memory and fires up the oomkiller.

    pid 616 (varnishd), uid 80, was killed: out of swap space
    pid 620 (postgres), uid 70, was killed: out of swap space
    pid 622 (postgres), uid 70, was killed: out of swap space
    pid 623 (postgres), uid 70, was killed: out of swap space
    pid 621 (postgres), uid 70, was killed: out of swap space
    pid 618 (postgres), uid 70, was killed: out of swap space
    pid 77182 (varnishd), uid 80, was killed: out of swap space
    pid 628 (php-fpm), uid 0, was killed: out of swap space
    pid 316 (devd), uid 0, was killed: out of swap space
    pid 3225 (sshd), uid 1001, was killed: out of swap space
    pid 3221 (sshd), uid 0, was killed: out of swap space
    pid 79223 (dma), uid 1001, was killed: out of swap space
    pid 79099 (dma), uid 1001, was killed: out of swap space
    pid 79393 (dma), uid 1001, was killed: out of swap space
    pid 563 (varnishd), uid 0, was killed: out of swap space

Would it be feasible to have dma refuse to fire up send-mail and drop the message in the local queue if more than X send-mail processes are running? That might be a sane solution if you recommend that dma clear it's queue by cron regularly.

**Comment by corecode** [comment]
I don't recommend servicing the queue using cron.

I am surprised that the dma processes eat so much memory.  However,
creating any other process in such a number will lead to the same OOM
result, so I don't think this is a real DoS.

**Comment by feld** [comment]
Hang with me here -- 

You can normally limit a user's abilities to do things like with ulimit and other mechanisms: stop them from doing fork bombs or chewing up too much memory, etc. But in this scenario I'm sending mail via mail/sendmail -- it's actually dma being executed which on FreeBSD is setgid to the mail user.

How does this affect the ability to limit damage? My gut tells me even if it was setuid or setgid it wouldn't matter and the limits should still be enforced, but my brain tells me I shouldn't blindly trust my gut :)

**Comment by corecode** [comment]
dma will run as your user (it is not setuid), so the limit should be enforced.  Could you try whether this is indeed the case?

**Comment by feld** [comment]
yes, this can be closed
