### ISSUE TITLE
DNS lookup failures result in inconsistent bounce behaviour

### ISSUE THREAD

**Issue by sig11b** [corecode/dma#30]
I have the following setup: My system is supposed to have network connectivity and dma is supposed to send mail via SMARTHOST right away. However, occasionally, the connectivity drops and I want dma to take care of the queuing. But at that point, the SMARTHOST can no longer be resolved, and the message gets bounced. I have run 3 test scenarios, sending a mail to a host that can receive mail by itself (and not having an MX record):

Before the following: I disconnect from the network.

1. no SMARTHOST
May 27 08:54:02 alice dma[1fba5.21545c0]: trying delivery
May 27 08:54:02 alice dma[1fba5.21545c0]: remote delivery deferred: DNS lookup failure: host {destinationhost}.de not found

2. SMARTHOST as FQDN
May 27 08:54:56 alice dma[1fc69.12255c0]: trying delivery
May 27 08:54:56 alice dma[1fc69.12255c0]: using smarthost ({smarthostFQDN}.de:25)
May 27 08:54:56 alice dma[1fc69.12255c0]: remote delivery failed: DNS lookup failure: host {smarthostFQDN}.de not found
May 27 08:54:56 alice dma[1fc69.12255c0]: delivery failed, bouncing as 1fc79
May 27 08:54:56 alice dma[1fc79]: new mail from user={USER} uid=8 envelope_from=<>
May 27 08:54:56 alice dma[1fc79]: mail to={SENDER-EMAIL-ADDRESS} queued as 1fc79.1226b30
May 27 08:54:56 alice dma[1fc79.1226b30]: trying delivery
May 27 08:54:56 alice dma[1fc79.1226b30]: using smarthost ({smarthostFQDN}.de:25)
May 27 08:54:56 alice dma[1fc79.1226b30]: remote delivery failed: DNS lookup failure: host {smarthostFQDN}.de not found
May 27 08:54:56 alice dma[1fc79.1226b30]: can not bounce a bounce message, discarding

3. SMARTHOST as IP address
May 27 08:56:03 alice dma[1fc69.12155c0]: trying delivery
May 27 08:56:03 alice dma[1fc69.12155c0]: using smarthost ({smarthostIP}:25)
May 27 08:56:03 alice dma[1fc69.12155c0]: trying remote delivery to {smarthostIP} [{smarthostIP}] pref 0
May 27 08:56:03 alice dma[1fc69.12155c0]: connect to {smarthostIP} [{smarthostIP}] failed: Network is unreachable

I end up with three mails in the queue and according to ps ax no running dma process.

ID      : 1fba5.21545c0
From    : {SENDER-EMAIL-ADDRESS}
To      : {RECEIVER-EMAIL-ADDRESS}

ID      : 1fc79.1226b30
From    :
To      : {SENDER-EMAIL-ADDRESS}

ID      : 1fc69.12155c0
From    : {SENDER-EMAIL-ADDRESS}
To      : {RECEIVER-EMAIL-ADDRESS}

I then reconnect and run dma -q

May 27 08:58:40 alice dma[1fc79.1226b30]: trying delivery
May 27 08:58:40 alice dma[1fc79.1226b30]: using smarthost ({smarthostIP}:25)
May 27 08:58:40 alice dma[1fc79.1226b30]: trying remote delivery to {smarthostIP} [{smarthostIP}] pref 0
May 27 08:58:46 alice dma[1fc79.1226b30]: delivery successful
May 27 08:59:02 alice dma[1fba5.21545c0]: trying delivery
May 27 08:59:02 alice dma[1fba5.21545c0]: trying remote delivery to {destinationhost}.de [{destinationIP}] pref 0
May 27 08:59:03 alice dma[1fc69.12155c0]: trying delivery
May 27 08:59:03 alice dma[1fc69.12155c0]: using smarthost ({smarthostIP})
May 27 08:59:03 alice dma[1fc69.12155c0]: trying remote delivery to {smarthostIP} [{smarthostIP}] pref 0
May 27 08:59:07 alice dma[1fba5.21545c0]: delivery successful
May 27 08:59:08 alice dma[1fc69.12155c0]: delivery successful

Scenario 1 and 3 then get deliverd as expected, and for scenario 2 I get a bounce message with this text in front:

This is the DragonFly Mail Agent v0.9 at alice.

There was an error delivering your mail to {RECEIVER-EMAIL-ADDRESS}.

DNS lookup failure: host {smarthostFQDN}.de not found

Message headers follow.

My dma.conf only contains a SMARTHOST entry (not for scenario 1) and a MASQUERADE entry to add a valid domain (like the example MASQUERADE percolator  will send mails as $username@percolator, e.g. fish@percolator)

I would expect that scenarios 2 and 3 should be treated equivalently. And also scenario 1 is not too different from 2. If this needs a fix, I would suspect the function add_host() to be the problem. And that after the call to getaddrinfo() more error codes than only EAI_AGAIN should make add_host() return a 1.

Alternatively, there could be an option like DEFER_INSTEAD_OF_BOUNCE_ON_CERTAIN_NETWORK_ERRORS (this is too long ;-) but you get the idea) for non permanent network connections.

**Comment by corecode** [comment]
thanks for the report.  I will fix it as soon as I get the chance.

Of course if you can come up with a patch, I would be happy to review
and pull the fix.
