### ISSUE TITLE
local.c From sender<TAB>timedate breaks mail.mailutils

### ISSUE THREAD

**Issue by gregorlarson** [corecode/dma#38]
The use of a TAB (\t) character when generating the From line in local.c may not be correct.
Granted the standards don't explicitly say a space is used to separate, however, some mail clients don't seem to handle the tab character correctly (http://mailutils.org/).

**Comment by gregorlarson** [comment]
[patch.txt](https://github.com/corecode/dma/files/110629/patch.txt)

**Comment by corecode** [comment]
Thanks, committed!  Next time please use a pull request, instead of attaching the patch.
