### ISSUE TITLE
Local email delivery for cron output

### ISSUE THREAD

**Issue by sunaku** [corecode/dma#48]
Hello,

I'm trying to set up local email delivery for cron output in [Void Linux](http://www.voidlinux.eu/) using:
- **dcron** - Dillon's lightweight cron daemon
- **dma** - Small Mail Transport Agent (MTA), designed for home and office use
- **mailx** - Feature-rich BSD mail(1)

I've installed the above packages, enabled the **dcron** service, and ran a test:

```
$ echo hello world | mail -s testing $USER
```

Immediately after, I can see that **dma** has accepted and queued that email:

```
$ ls /var/spool/dma
Q1fef0.564ce8239eb0  M1fe62.564952c5feb0

$ dma -bp
ID      : 1fef0.564ce8239eb0
From    : void@linux
To      : void
```

However, when I use **mailx** to read that email message, it's unable to access it:

```
$ mail
No mail for void
```

I've also ran `dma -q` to manually flush the queue, but it didn't affect **mailx**.

How do I make **dma** deliver email to **mailx** so that I can read my cron output?

Thanks for your consideration.

> P.S.  I've also asked [this question on the Void Linux Forum](https://forum.voidlinux.eu/t/local-email-delivery-for-cron-output/1161) without much success. :confounded:

**Comment by corecode** [comment]
what are the permissions on the queue files and directory?

**Comment by sunaku** [comment]
Hey, thanks for the response :+1: and sorry for my delay! :sweat:  Here are the permissions you requested:
```ls
drwxrwsr-x 2 root mail 4.0K Jun 25 12:02 /var/spool/dma
-rw-rw---- 1 void mail  328 Oct  2  2016 /var/spool/dma/M1fe62.564952c5feb0
-rw-rw---- 1 void mail   62 Oct  2  2016 /var/spool/dma/Q1fe62.564952c5feb0
```

However, everything magically started working (without any effort on my part) earlier this year. :sweat_smile:  I'll see if I can still reproduce this issue on another machine on which I recently set up a brand new Void Linux install.

**Comment by reedjc** [comment]
dma would log about problems writing to the mbox.
