### ISSUE TITLE
different behavior when called as "mailq" then "/usr/bin/mailq"

### ISSUE THREAD

**Issue by Mask66** [corecode/dma#51]
We ran into problems calling dma (on FreeBSD) from the nagios check_mailq script, and found out that it behaves correctly when called as just "mailq", but incorrectly when called as "/usr/bin/mailq" (with a path) for example. This patch (see pull request #52) written by my colleague Klaus-Uwe Ittner corrects this. 

Also reported as `https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216910.`

**Comment by corecode** [comment]
commited, thanks!
