### ISSUE TITLE
Incorrect Error Check of SSL_connect() in dma/crypto.c 

### ISSUE THREAD

**Issue by lc3412** [corecode/dma#59]
Hi,
Function SSL_connect()  returns the value of 0 and less than 0  are both on error. However , the return value of  function SSL_connect() in dma/crypto.c is not checked correctly, which forgot to check the return value 0. See the following code:

![screenshot from 2018-09-13 19-58-13](https://user-images.githubusercontent.com/19151593/45487002-9ef71780-b78f-11e8-8a65-416794e9b2e1.png)

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by lc3412** [comment]
> Hi,
> Function SSL_connect() returns the value of 0 and less than 0 are both on error. However , the return value of function SSL_connect() in dma/crypto.c is not checked correctly, which forgot to check the return value 0. See the following code:
> 
> ![screenshot from 2018-09-13 19-58-13](https://user-images.githubusercontent.com/19151593/45487002-9ef71780-b78f-11e8-8a65-416794e9b2e1.png)
> 

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2. 
Such as in openssl/apps folder

apps/s_time.c
ref: https://github.com/openssl/openssl/blob/master/apps/s_time.c
![screenshot from 2018-09-13 23-15-19](https://user-images.githubusercontent.com/19151593/45497666-f22a9380-b7aa-11e8-8f91-9df15a038cbe.png)


> Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by lc3412** [comment]
> Hi,
> Function SSL_connect() returns the value of 0 and less than 0 are both on error. However , the return value of function SSL_connect() in dma/crypto.c is not checked correctly, which forgot to check the return value 0. See the following code:
> 
> ![screenshot from 2018-09-13 19-58-13](https://user-images.githubusercontent.com/19151593/45487002-9ef71780-b78f-11e8-8a65-416794e9b2e1.png)
> 
> Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by corecode** [comment]
why did you close this?

**Comment by lc3412** [comment]
> 
> 
> why did you close this?

Sorry, My operation error. Already reopen it.

**Comment by corecode** [comment]
Fixed in 41141e0073846b0e3cdde6de335313abeb19c4b4
