### ISSUE TITLE
Incorrect Error Handling of  strchr() in  dma/ dma-mbox-create.c

### ISSUE THREAD

**Issue by lc3412** [corecode/dma#63]
Function strchr() returns return a pointer to the matched character or NULL if the character is not found. However , the return value of function strchr() in  dma/ dma-mbox-create.c is wrong checked?  See the following code:

https://github.com/corecode/dma/blob/e2a4592ccc4e4b2f1b92ce3532af4adba3cf1c50/dma-mbox-create.c#L120-L125

The correct useness is may be change the error check into 
```c
if (!strchr(user, '/')) {
		errno = 0;
		logfail(EX_DATAERR, "path separator in username `%s'", user);
		exit(1);
}
```

**Comment by corecode** [comment]
The original code seems correct.  What do you think the problem is?

**Comment by lc3412** [comment]
Sorry , I got that wrong. Thanks for your time and explanation :)
