### ISSUE TITLE
Multiple addresses in RCPT TO:

### ISSUE THREAD

**Issue by jailbird777** [corecode/dma#73]
Looks like Netscape/Sun/iPlanet/Oracle SMTP server doesn't like multiple addresses in a RCPT TO: line.  Eg, it'll completely reject:

RCPT TO:<addr1@example.com,addr2@example.com,addr3@example.com>

But it WILL accept multiple RCPT TO:'s with one address each, eg:

RCPT TO:<addr1@example.com>
RCPT TO:<addr2@example.com>
RCPT TO:<addr3@example.com>

it looks like sSMTP does the multiple RCPT TO thing, probably for the same reason (or maybe so that it can tell which addresses get accepted and which don't?):  https://github.com/ajwans/sSMTP/blob/master/ssmtp.c#L1642

I did the same basic hack locally to dma to make it work the same way, pull out a nasty strtok() for a comma :(.

**Comment by jailbird777** [comment]
RFC5321 section 4.1.1.3 https://tools.ietf.org/html/rfc5321#section-4.1.1 seems to explicitly require one address per RCPT TO, so it seems like the existing dma behavior is non-compliant.

**Comment by corecode** [comment]
please share your patch in a pull request.  Why do we even have multiple
RCPT TO?  shouldn't the mail have been split up into multiple deliveries?

**Comment by jailbird777** [comment]
PR @ https://github.com/corecode/dma/pull/74

It looks like the only splitting is when sending to different multiple hosts.  In this case of multiple addresses to the same MX or using smarthost, it doesn't appear that it's normally split up.
