### ISSUE TITLE
Should "mail root" respect the /etc/aliases settings with dma? 

### ISSUE THREAD

**Issue by trevor87** [corecode/dma#80]
Hi!

I have been trying for hours to figure this out but did not manage, therefore I wanted to ask here.

I installed dma on a raspberry pi with the current ubuntu server and set everything up to work with gmail. I also configured `/etc/aliases` with an e-mail adress e.g. "john@doe.com" for root.

When I use `dma root` the mails arrive just fine in my inbox at "john@doe.com". When I do `mail root` according to /var/log/mail.log the mails go to "root@my.router".

**Is this to be expected? Does this have anything to do with dma?**

**Also, should the `mail` command work out of the box with dma or does one need to install mailutils first?** Please excuse my possibly dumb question, I just saw that `mail` is the way to test dma on (this)[https://wiki.mageia.org/en/Dma_Dragonfly_Mail_Agent] site and it didn`t work for me out of the box.

**Comment by corecode** [comment]
You need mailutils if you want the mail command.  mail is not part of dma.  dma should read the aliases file and also apply it for root.

**Comment by foresto** [comment]
> dma should read the aliases file and also apply it for root.

Confirming with dma 0.12: It does indeed do that. :)
