### ISSUE TITLE
Command alias "newaliases"

### ISSUE THREAD

**Issue by colazivi** [corecode/dma#83]
Hello,

https://github.com/corecode/dma/blob/14ea7d7d5b8e0819d462c9265dafd1b222d994c1/dma.c#L467-L474

Is this command alias still necessary (I don't see it being created by make)? If so, it should also use basename(3) like for "mailq" (see below). At the moment the check doesn't work for it being run as for example ./newaliases or/path/to/newaliases

Compare to:
https://github.com/corecode/dma/blob/14ea7d7d5b8e0819d462c9265dafd1b222d994c1/dma.c#L461

**Comment by corecode** [comment]
I think having the alias is useful, because some systems expect newaliases to exist.  Those systems can easily create a symlink.

I agree that we should use basename.
