### ISSUE TITLE
aliases line 0: syntax error

### ISSUE THREAD

**Issue by trickert76** [corecode/dma#84]
I have an aliases file in /etc/dma/aliases that I've mentioned in /etc/dam/dma.conf. I'm getting:

```
Aug 11 00:30:02 ac-hcn0002 dma: aliases line 0: syntax error
Aug 11 00:30:02 ac-hcn0002 dma: could not parse aliases file `/etc/dma/aliases': Success
```

The file contains only one line:

```
root:	postmaster@domain.de
```

My problem is: I can't find a suitable documentation of the format of that file.

**Comment by corecode** [comment]
make sure you have a newline at the end of the file

**Comment by trickert76** [comment]
Ok, that works. Would it be a good idea, to make somewhere a note?
